version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 3600